### PR TITLE
Added Dockerfile to provide a working build environment

### PR DESCRIPTION
**Pull request by weltoph**
Having experienced some trouble building this project, I created a Dockerfile which sets up an environment to build and use `dWiNA`. Additionally, this environment re-builds the required dependencies from libvata and MONA since the build process failed for me with the provided ones.

### CODE REVIEW

**Comment by tfiedor** [comment]
Thank you, Christoph, for containerization of the dWiNA. Though, I will repeat, that dWiNA has been deprecated for some time, and our other tool (gaston) should be (1) more stable, and (2) more advanced.

Cheers.

**Comment by weltoph** [comment]
Thanks for reacting so promptly! Is there any further development on Gaston? There still is a [regression](https://github.com/tfiedor/gaston/issues/6) between Gaston and MONA. I'd be very interested in using lazy WS1S solvers for my research since I repeatedly run into MONA's restrictions.

**Comment by tfiedor** [comment]
I know about the issue, unfortunately (as I mentioned) I have been working on different projects so I have found no time so far to look at it. We have some other research regarding the WS2S, however, the resulting tool is rather prototype and I am not sure if it is available to public.

What kinds of MONA's restrictions have you ran into? You mean, that it timeouts on some formulae?

**Comment by weltoph** [comment]
Either MONA aborts due to reaching a limit on the constructed BDD or while constructing the automata it is killed for its memory consumption. Since I am only checking for unsatisfiability of specifically formed formulae I was putting some hope into Gaston's under-approximations.

**Comment by tfiedor** [comment]
Well, you are not the first one to hit that brick wall. Do you, perhaps, have those formulae uploaded somewhere? I could forward them to my colleagues, who are still working on WSkS and I think they would be interested in more, challenging formulae.

As for the limits of the MONA, in our experience, we usually tried to or advised to:
  1. Simplify the formulae (especially reducing the number of variables reduces the size of the BDD considerably) 
  2. Try to use gaston's optimizations with MONA (i.e. run `./gaston --serialize --dry-run formula.mona` which should output `serialized_formula.mona` that can be checked by MONA). We employ lots of optimization on formula level (most notably the anti-prenexing) and they tend to help in other decision procedures as well. So you could try to run `mona` with the `serialized_formula.mona`.

**Pull request merged**
